name: Playwright Pytest + Allure

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run tests and generate Allure results
        run: pytest --alluredir=allure-results

      - name: Install Allure commandline
        run: |
            wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
            tar -zxvf allure-2.27.0.tgz
            sudo mv allure-2.27.0 /opt/allure
            sudo ln -s /opt/allure/bin/allure /usr/bin/allure


      - name: Generate Allure HTML report
        run: |

          allure generate allure-results -o allure-report --clean

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
